describe(`Lesson 31 handle a rejected promise with catch`, () =>{
	test(`You should call the <code>catch</code> method on the promise.`, () =>{
		//test goes here
	})
	test(`Your <code>catch</code> method should have a callback function with <code>error</code> as its parameter.`, () =>{
		//test goes here
	})
	test(`You should log <code>error</code> to the console.`, () =>{
		//test goes here
	})
})